### PR TITLE
Link to Dear GitHub, fix #551

### LINKED ISSUE #551: Link to Dear Github?
https://github.com/dear-github/dear-github/

### PR DESCRIPTION
**Pull request by cirosantilli**
#551

### CODE REVIEW

**Comment by Stargator** [comment]
:+1:

**Comment by TPS** [comment]
:+1: :100:%

**Comment by Schweinepriester** [comment]
+1

**Comment by JLLeitschuh** [comment]
+1

**Comment by TPS** [comment]
@cirosantilli Time to merge, no?

**Pull request merged**
