### PR TITLE
Send issue URL to GitHub

### PR DESCRIPTION
**Pull request by cirosantilli**

### CODE REVIEW

**Comment by stuartpb** [comment]
[:+1:](#6)

**Comment by TPS** [comment]
@isaacs @cirosantilli Is this now complete, or still under discussion someplace?

**Comment by cirosantilli** [comment]
@TPS let's give it a week now that you've mentioned Isaacs, otherwise I'll just merge.

**Comment by cirosantilli** [comment]
Waited long enough, merging.

**Pull request merged**
