### PR TITLE
Replace support@github.com with support.github.com

### PR DESCRIPTION
**Pull request by kristianvld**
Suggest filing feedback, issues and feature requests through GitHubs support.github.com page as they no longer allow support requests to be opened through their email.

Support requests to support@github.com will automatically be responded with an answer telling you to file a request over at https://support.github.com, at least as of current date (February, 2020).

### CODE REVIEW

**Comment by TPS** [comment]
Duplicates #1735

**Comment by kristianvld** [comment]
Somehow missed to check that issue before creating my own, sorry about that.

Do notice though that this merge also updates the info of the `CONTRIBUTING.md`, which also has a reference to the support@github.com email, while #1735 does not.

**Comment by TPS** [comment]
@kristianvld There _is_ that.  Do you mind resolving the current merge conflict?

**Comment by TPS** [comment]
Nm, got it.

**Pull request merged**
